config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#show'

  post '/users', to: 'users#create'
  get '/register', to: 'users#new'
  get '/favorites/:user_id', to: 'favorites#index', as: '/favorites'

  post '/sessions', to: 'sessions#create'
  get '/login', to: 'sessions#new'

  get '/recipes/:user_id', to: 'recipes#index', as: '/recipes'

  get '/country/:name', to: 'country#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_login
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id] && session[:api_key]
      @current_user_id ||= session[:user_id]
      @current_user_api_key ||= session[:api_key]
    end
  end

  def logged_in?
    current_user != nil
  end

  def check_login
    if !logged_in?
      flash[:error] = "You must be logged in to view this content"
      redirect_to '/'
    end
  end
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def show
    @resources = LearningResourcesFacade.new(params).find_resources_by_country
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :find_user, only: %i[discover show]
  skip_before_action :check_login, only: [:new, :create]
  skip_before_action :verify_authenticity_token

  def new; end

  def index; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_user, only: %i[discover show]
  skip_before_action :check_login, only: [:new, :create]
  skip_before_action :verify_authenticity_token

  def index
    if params[:country]
      @recipes = RecipesFacade.new(params).find_recipes_by_country
      @message = RecipesFacade.new(params).get_message
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_user, only: %i[discover show]
  skip_before_action :check_login, only: [:new, :create, :destroy ]
  skip_before_action :verify_authenticity_token

  def new; end

  def create
    user = UsersFacade.new(user_params).find_user
    if user
      reset_session
      session[:user_id] = user.id
      session[:api_key] = user.api_key
      flash[:success] = "Welcome, #{user.email}"
      redirect_to recipes_path(session[:user_id])
    else
      flash[:error] = "Unknown username or password"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end

  private

  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[discover show]
  skip_before_action :check_login, only: [:new, :create]
  skip_before_action :verify_authenticity_token

  def new; end

  def create
    new_user = UsersFacade.new(user_params).create_user
    if new_user
      reset_session
      session[:user_id] = new_user.id
      session[:api_key] = new_user.api_key
      flash[:success] = "Welcome, #{new_user.email}"
      redirect_to recipes_path(session[:user_id])
    else
      redirect_to register_path
      flash[:alert] = UsersFacade.new(user_params).post_message
    end
  end

  private

  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :current_user
  skip_before_action :check_login
  skip_before_action :verify_authenticity_token

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/country/show.html.erb
<br><center><h1 style="font-family: Comic Sans MS"><%= @resources.country %><h1><center><br>

<div class="container">
  <iframe width="750" height="450" src="https://www.youtube.com/embed/<%= @resources.video[:youtube_video_id] %>"></iframe>
</div><br>

<div class="container" style="width: 1000px">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <% (@resources.images.count - 1).times do %>
        <% count = 1 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<% count %> "></li>
        <% count += 1%>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="<%= @resources.images[0][:url] %>" alt="<%= @resources.images[0][:alt_tag] %>">
        <div class="carousel-caption d-none d-md-block">
          <p class="h6"><%= @resources.images[0][:alt_tag]%></p>
        </div>
      </div>
      <% @resources.images.shift %>
      <% @resources.images.each do |image| %>
        <div class="carousel-item">
          <img class="d-block w-100" src="<%= image[:url]%>" alt="<%= image[:alt_tag] %>">
          <div class="carousel-caption d-none d-md-block">
            <p class="h6"><%= image[:alt_tag]%></p>
          </div>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<div>

app/views/favorites/index.html.erb
<h1> Favorites </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchAndLearnFrontEnd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <% flash.each do |type, msg| %>
    <div style="color:red;font-weight:bold;">
      <%= msg %>
    </div>
    <% end %>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="/">Home</a>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <a class="nav-link active" href="/recipes/<%=@current_user_id%>">Find Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/favorites/<%=@current_user_id%>">My Favorites</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/logout">Log Out</a>
        </li>
      <% end %>
    </ul><br><br>
    <h1><center>Lunch and Learn</center></h1>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/index.html.erb
<body>
  <div class='flex-container'>
    <div class="flex-items" id="title">
      <h3>Find Recipes By Country<h3>
    </div>

    <div class="flex-items" id="find_recipes_by_country_form">
      <%= form_with url: recipes_path, method: :get, local: true do |f| %>
        <%= f.label :country %>
        <%= f.text_field :country %>

        <%= f.submit "Find Recipes", class: 'button1' %>
      <% end %> <br>
    </div>

    <div class='flex-items' id= 'random_country_button'>
      <%= button_to "Choose a Country for me!", recipes_path, method: :get, params: { country: 'random' }, class: 'button1' %>
    </div>

    <div class='flex-items' id= 'my_favorites_button'>
      <%= button_to "Show me my favorites", favorites_path(@current_user_id), method: :get, class: 'button1' %>
    </div>
  </div><br>

  <div class='flex-container'>
    <% if @recipes && !@recipes.empty? %>
      <div class='flex-items' id= 'learn_about_country_button'>
        <%= link_to "Learn about #{@recipes.first.country}", "/country/#{@recipes.first.country}", class: "btn btn-info" %>
      </div>

      <div class='cards' id='cards'>
        <% @recipes.each do |recipe| %>
          <article class='card'>
            <img src=<%="#{recipe.image}"%>>
            <div class='text'>
              <h3 style="text-decoration: none;"><%= link_to recipe.title, "#{recipe.url}" %></h3>
            </div>
          </article>
        <% end %>
      </div>
    <% elsif @recipes && @recipes.empty? %>
      Please try again
    <% end %>
  </div>
</body>

app/views/users/new.html.erb
<body>
  <div class='flex-container'>
    <div class="flex-items" id="title">
      <h3>Register a New User<h3>
    </div>

    <div class="flex-items" id="new_user_form">
      <div id="register-form">
      <%= form_with url: users_path, method: :post, local: true do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, required: true %><br><br>

        <%= f.label :email %>
        <%= f.email_field :email, required: true %><br><br>

        <%= f.label :password %>
        <%= f.password_field :password, required: true, pattern: '^(?=.*[A-Za-z])[A-Za-z\d]{4,}' %><br><br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, required: true, pattern: '^(?=.*[A-Za-z])[A-Za-z\d]{4,}' %><br><br>

        <%= f.submit "Create New User", class: 'button1' %>
      <% end %>
    </div>
  </div>
</body>

app/views/welcome/show.html.erb
<body>
  <div class='flex-container'>
    <div class="flex-items" id="new_user_button">
      <%= button_to 'Create a New User', register_path, method: :get, class: 'button1' %>
      <%= button_to 'Log In', login_path, method: :get, class: 'button1' %>
    </div>
  </div>
</body>